In [7]:
import numpy as np
import pandas as pd
from scipy.special import expit

# Sample data setup
np.random.seed(0)
data = pd.DataFrame({
    'cost.car': np.random.randn(1000),
    'time.car': np.random.randn(1000),
    'time.bus': np.random.randn(1000),
    'choice': np.random.randint(0, 2, size=1000)
})

# Initial parameters (4 parameters including the intercept)
params = np.random.randn(4)

def mm_fn(params, data):
    X = data[['cost.car', 'time.car', 'time.bus']]
    X = np.hstack([np.ones((X.shape[0], 1)), X])  # Add intercept term (constant)
    y = data['choice'].values
    prob = expit(np.dot(X, params))  # Sigmoid function to get probabilities
    error = y - prob
    return error[:, np.newaxis] * X

def compute_jacobian_and_sum(params, data):
    X = data[['cost.car', 'time.car', 'time.bus']]
    X = np.hstack([np.ones((X.shape[0], 1)), X])  # Add intercept term (constant)
    y = data['choice'].values
    prob = expit(np.dot(X, params))  # Sigmoid function to get probabilities
    
    # Initialize the sum of Jacobians as a zero 4x4 matrix
    sum_jacobian = np.zeros((4, 4))
    
    # Loop through each data point
    for i in range(len(y)):
        xi = X[i]  # 1x4 vector
        pi = prob[i]  # scalar
        error_i = y[i] - pi  # scalar
        
        # Gradient of the probability with respect to params: pi * (1 - pi) * xi
        gradient = pi * (1 - pi) * np.outer(xi, xi)  # 4x4 matrix
        
        # Contribution to the Jacobian from the i-th data point
        jacobian_i = -gradient  # 4x4 matrix
        
        # Sum the Jacobian
        sum_jacobian += jacobian_i
    
    return sum_jacobian

# Calculate the sum of Jacobians
sum_jacobian = compute_jacobian_and_sum(params, data)

# Output the final summed Jacobian matrix
print("Sum of Jacobians:\n", sum_jacobian)

Sum of Jacobians:
 [[-157.06916187    2.48084928   42.43273387   -9.26815087]
 [   2.48084928 -148.38546532   -5.59409383   12.64423919]
 [  42.43273387   -5.59409383  -97.09308495  -20.79645583]
 [  -9.26815087   12.64423919  -20.79645583 -131.70005231]]
